language: android
before_install:
  - nvm install 13
  - node --version
  - openssl aes-256-cbc -K $encrypted_46cc22d23cb5_key -iv $encrypted_46cc22d23cb5_iv -in android/gds-upload-keystore.jks.enc -out android/app/gds-upload-keystore.jks -d
install:
  - npm install
  - yes | sdkmanager "platforms;android-28"
  - touch .env
  - echo "API_URL=http://gds.proepi.org.br" > .env
  - echo "APP_ID=1" >> .env
android:
  components:
  - build-tools-29.0.1
  - android-29
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
  - cd android && ./gradlew assembleRelease
  - cp app/build/outputs/apk/app-release.apk ..
  - cd ..
  - ls
  - ls android
  - ls android/app/
  - ls android/app/build/
  - ls android/app/build/outputs/
  - ls android/app/build/outputs/apk/
after_success:
deploy:
  provider: releases
  api_key:
    secure: KY3aD1tRT89JvZ5KWzvoHFL4x0ajC17aREvZcC0ZwHgBtr2t+YwCSFSOzAXqZxjEYy3EnzmQaR0ZJ7kxIzvy1PwbbgJc485QZfpgVGYodgm+T3Asoq/abW1CCnRR5/gs0fqUD8EqJMU2cLQ4ciaeu3NGTEh7jfTq7nkN/8v/+4rOGJrQjClmo0Q4J8l0Cf6qCMSKIYIDz76DgyPumyw4eJMmPiuPhnYSLuyMIrI28+hDOhV7a2N/VErX6u8tlPXz+e3veDbaRsx23IlILC4P9FxjxQzgK+77/URBj2cq08ZAKzvC5DebcjzQyZgxd8QSmaO+mX0D+rxNLp54Li1dkM9XiCbc4qx1XIusWgu7eLJNh1xcMPq/JkWFD3sD2coGW25yV7yZQQMERvsiU4vsK0vxGrn4eyoY8OS+SnvX9kJJACp/HeQPJGPsgVHnPGPJHGu5AhPXsBtyo0LtiQMcQ2/BIQQ259hv15xk9/kTsrORuP0VOJ4tV9gaOmM6dWF6FCjSitphpdn6iICEfCNkk81/XN659VTckcVtga+V28uj2moRSK1wjYIgB1Tklvav21dNYgM7k7o31p15Rxggu+teDO/GaAM8xpNW9Ux3RHeYu2Y85u1YjgcPkNU3KN2kmx/Av6OYPzPrUOh8DQcS5pq842IyUYUzgj0/eA8+QC0=
  file: "android/app/build/outputs/apk/app-release.apk"
  on:
    repo: RenatoBrittoAraujo/guardioes-app
    branch: feature/ci-travis
  skip_cleanup: 'true'
